package com.murvetarslan.gezirehberiuygulamasi;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.widget.ScrollView;

//Bu sınıf verilerin saklandığı sınıf.
public class DatabaseHelper extends SQLiteOpenHelper {
    private static final String DATABASE_NAME = "my_database"; //Database in ismi tanımlama
    private static final int DATABASE_VERSION = 1; //Database in versiyonu


    public DatabaseHelper(Context context) { //DatabaseHelper ın yapıcı metodu
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        // my_table adında tablo oluşturup bu tabloya şehirleri ekliyorum
        db.execSQL("CREATE TABLE sehirler_tablo (sehirPlaka INTEGER, name TEXT)");
        db.execSQL("INSERT INTO sehirler_tablo (sehirPlaka,name) VALUES (0,'Şehir Seçin')");
        db.execSQL("INSERT INTO sehirler_tablo (sehirPlaka,name) VALUES (1,'Adana')");
        db.execSQL("INSERT INTO sehirler_tablo (sehirPlaka,name) VALUES (2,'Adıyaman')");
        db.execSQL("INSERT INTO sehirler_tablo (sehirPlaka,name) VALUES (3,'Afyonkarahisar')");


        // ozellik_table adında tablo oluşturup bu tabloya özellikleri ekliyorum
        db.execSQL("CREATE TABLE ozellik_tablo (ozellikId INTEGER,ozellikAd TEXT)");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (0,'Özellik seçin')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (1,'Genel Bilgi')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (2,'Gezilecek Yerler')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (3,'Tarih')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (4,'Yemekler')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (5,'Yöresel')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (6,'Ulaşım')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (7,'Hava Durumu')");
        db.execSQL("INSERT INTO ozellik_tablo (ozellikId,ozellikAd) VALUES (8,'Müzik')");

        //db.execSQL("CREATE TABLE bilgiler_tablo (id INTEGER,sehirId INTEGER,baslik TEXT,aciklama TEXT,FOREIGN KEY (sehirId) REFERENCES sehirler_tablo(sehirPlaka))");

        db.execSQL("CREATE TABLE bilgiler_tablo (ozID INTEGER,sehirId INTEGER,baslik TEXT,aciklama TEXT,FOREIGN KEY (sehirId) REFERENCES sehirler_tablo(sehirPlaka),FOREIGN KEY (ozID) REFERENCES ozellik_tablo(ozellikId))");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (1,1,'','Adana,Türkiyenin bir ili ve en kalabalık yedinci şehridir.2021 yılı verilerine göre 2.263.373 nüfusa sahiptir.İlin yüzölçümü 13.844km2dir.İlde km2ye 163 kişi düşmektedir en yüksek Seyhan ilçesinde 1.785 kişi 04.02.2021 TÜİK verilerine göre 5 i merkez ilçe (Seyhan,Yüreğir,Çukurova,Sarıçam,Karaisalı) olmak üzere toplam 15 ilçesi ve belediyesi vardır.Bu ilçelerde 831 mahalle bulunmaktadır.Adana; kuzeyinde Kayseri, doğusunda Osmaniye, kuzeydoğusunda Kahramanmaraş, güneydoğusunda Hatay, kuzeybatısında Niğde ve batısında Mersin illeri ve güneyinde Akdeniz ile çevrilidir.Türkiyedeki altıncı büyük metropolitan alan olup ülkenin önde gelen tarım, ticaret ve kültür merkezlerinden biridir. Türkiyedeki maden zengini 4. bölge olan Adana;krom,demir,manganez,kurşun ve çinko yatakları açısından önem taşımaktadır.Adananın merkezi;Mersin, Adana,Osmaniye ve Hatay illerini kapsayan coğrafi, ekonomik ve kültürel bir bölge olan Çukurovanın merkezinde bulunur.Yaklaşık 6,33 milyon insana ev sahipliği yapan bölgenin büyük bir bölümü, tarıma oldukça elverişli, geniş ve düz bir arazidir.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (1,2,'','Adıyaman,Türkiyenin Güneydoğu Anadolu Bölgesinin Orta Fırat Bölümünde bulunan bir ilidir.İdari merkezi Adıyaman şehridir.TÜİK 2021 sonu verilerine göre ilin nüfusu 632.459dur.Doğusunda Diyarbakır, kuzeyinde Malatya, batısında Kahramanmaraş, güneyinde Gaziantep ve Şanlıurfa illeri ile çevrilidir.İlin doğusunda Torosların güneydoğu uzantısı olan Malatya dağları, güneydoğusunda Atatürk Baraj Gölü yer alır.Doğusundan Fırat Nehri ile çevrilidir. İlin kuzey kesimi genel anlamda dağlık ve engebeli iken güney kesiminde geniş ovalar bulunur.İl sınırları içerisindeki tek üniversite Adıyaman Üniversitesidir.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (1,3,'','Afyonkarahisar, Ege Bölgesinin İç Batı Anadolu Bölümünde yer alan bir ildir.İl nüfusu 747.555tir (31 Aralık 2022). Bu nüfusun %78,07 ü şehirlerde yaşamaktadır (31 Aralık 2021). İlin yüzölçümü 14.016 km² dir.İlde km² ye 53 kişi düşmektedir.(Bu sayı merkez ilçede 253’dür.) Afyonkarahisar sınırlarında merkez ilçeyle beraber 18 İlçe, 60 belediye,bu belediyelerde 448 mahalle ve ayrıca 420 köy vardır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (2,1,'Sabancı Merkez Camii','Adanada ana arterlerin, demiryolunun ve çevre il ve ilçelere bağlayan yolların kesiştiği noktada bulunan, 1998 yılında hizmete açılan bir camidir. Cami, toplamda 58.900 m2 alan üzerine kurulmuş olup, 12.900 m2 kapalı alana sahiptir. Yüksek minareleriyle uzaktan görünen ve Adananın sembolü haline gelen bu cami, Balkanların ve Ortadoğunun en büyük camilerinden biridir. Seyhan Irmağı kenarında yer alan bu görkemli yapı, 6 minaresi ve 32 metre çapındaki kubbesiyle dikkat çeker. Kubbenin namaz kılınan kot itibariyle yüksekliği 54 metredir. Cami, 28.500 kişiye ibadet imkanı sunmakta olup, 4 ders odası, 10 itikaf odası, imam ve müezzin odaları, sohbet odaları ve şadırvan gibi imkanlara sahiptir. Cami, Mimar - Mühendis Necip Dinç tarafından tasarlanmış ve inşa edilmiştir. Camideki hat eserleri Hattat Hüseyin Kutluya, çiniler ise klasik İznik çini tekniği ile yapılmıştır. Cami içerisindeki tüm nakış eserleri ve çinilerin desenleri Mimar Nakkaş M. Semih İrteşe aittir. Ayrıca camide mermer mihrap, minber, kürsü, taç kapı ve diğer kapılar bulunmakta olup, ahşap kapılar kündekari tarzında Ahmet Yılçay tarafından yapılmıştır. Cami minareleri ise beyaz çimento ile fil dişi renginde kırma malzeme karıştırılarak elde edilen betondan inşa edilmiştir. Caminin iç ve dış aydınlatma projeleri ile iç seslendirme projeleri Philips tarafından çizilmiş ve Philips malzemeleri kullanılarak gerçekleştirilmiştir. Ayrıca camide Aselsan tarafından sağlanan merkezi telsiz yayını ile vaaz yayını yapılan bir merkezi yayın sistemi bulunmaktadır. Caminin batı kısmında ise araştırmacılara ve halka hizmet vermek üzere klasik ve dijital bir kütüphane yer almaktadır. Özel dini günlerde ise Sebil Çeşmesinden bal şerbeti sunulmaktadır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (2,1,'Taş Köprü','Adana Taş Köprü Seyhan Nehri üzerindedir. IV. (385) yüzyılda Roma İmparatoru Hadrianus tarafından yaptırılmıştır.Yüzyıllarca Avrupa ile Asya arasında önemli bir köprü olmuştur. Harun Reşit (766-809) köprüyü bazı eklerle Adana Kalesine birleştirmiştir.IX. yüzyıl başında Harun Reşit’in oğlu olan 7 inci Abbasi Halifesi Memun (786-833) tarafından onartılmıştır. III. Ahmet (1713), Kel Hasan Paşa (1847) ve Adana Valisi Ziya Paşa (1789) tarafından da değişik zamanlarda tamirat görmüştür. Bu üç onarımının yazıtları mevcuttur. Son onarım 1949 yılında yapılmıştır.Taş Köprü 319 metre uzunluğunda ve 13 metre yüksekliğindedir. 21 kemerinden 14’ü ayaktadır. Ortadaki büyük kemerde iki aslan kabartması görülmektedir.Dünyanın halen kullanılan en eski köprülerden biri olarak bilinmektedir.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (2,2,'Nemrut Dağı','Nemrut Dağı, Türkiye nin Adıyaman ilinde yer alan 2.150 metre yüksekliğinde bir dağdır.Adıyamanın Kahta ilçesinde yer alan Nemrut Dağı, Ankar Dağları civarında Toros dağ silsilesinde bulunur.[2] 1987 de UNESCO tarafından Dünya Mirası ilan edilen Nemrut Dağı,1988 yılında tesis edilen Nemrut Dağı Millî Parkı ile korumaya alınmıştır. Nemrut Dağı Kültür rotası Adıyaman merkezde bulunan Perre Antik Kenti ile başlayıp sonrasında Kahta ilçesinde bulunan Karakuş Tümülüsü, Cendere Köprüsü ve Kanyonu, Komagene Medeniyetinin yazlık başkenti olan Arsemia Ören Yeri, Kahta Kalesi, Şeytan Köprüsü ve nihayetinde Nemrut Dağında son bulur.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (2,2,'Cendere Köprüsü','Cendere Köprüsü, Antik Cabinas (Cendere) Çayı üzerinde bulunan ve aynı zamanda Roma Köprüsü veya Septimius Severus Köprüsü olarak da bilinen bir yapıdır. Köprü, muhteşem bir kanyonun üzerinde yer aldığı için bu isimlerle anılmaktadır. Kâhta İlçesinden Nemrut Dağına doğru giderken Sincik-Kocahisar yol ayrımında bulunmaktadır. Köprü, Roma İmparatoru Septimius Severusun emriyle MS 193-211 yılları arasında Samsatta (Somasata) karargah kuran XVI. Lejyon tarafından inşa edilmiştir.Cendere Köprüsü, Antik Roma mimarisinin etkileyici bir anıtsal örneğidir. İki kemerden oluşan köprü, ana kemer ve tahliye kemerinden oluşmaktadır ve tonlarca ağırlığındaki düzgün kesme taşlar kullanılarak yapılmıştır. Köprünün genişliği 7 metre, yüksekliği 30 metre ve uzunluğu 120 metredir. En ilginç mimari özelliklerinden biri, harç kullanılmadan yapılmış olmasıdır. Köprü, her iki tarafından rampa şeklinde yükselerek orta kısımda birleşmektedir. Bu özellik, köprünün statik dayanıklılığını artırmakta ve anıtsal bir görünüm kazandırmaktadır.Köprünün güney girişinin her iki tarafında korint düzeninde birer sütun bulunmaktadır. Bu sütunlar üzerindeki yazıtlardan biri, köprüyü yaptıran İmparator Septimius Severusa, diğeri ise onun karısı Julia Domna adına dikildiğini göstermektedir. Kuzey girişinin bir tarafındaki sütun üzerindeki yazıt ise oğlu Caracalla adına dikildiğini belirtmektedir. Köprünün yapıldığı dönemde kardeşi Geta adına dikilen bir sütun daha olduğu bilinmektedir, ancak Caracallanın Getayı öldürterek ona ait tüm anıtları yıktırmasıyla bu sütun da kaldırılmıştır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (2,3,'Karahisar Kalesi','Afyonkarahisar Kalesi, Afyonkarahisar şehir merkezinde volkanik özellikli, yerden yüksekliği 226 metre olan doğal yükseltili bir kaya kütlesi üzerinde yer alan bir kaledir.MÖ 1350 yıllarında Hitit imparatoru II. Murşil zamanında Arzava seferinde mustahkem mevki olarak kullanılmış olan bu kale önce Hapanuva; Roma ve Bizans dönemlerinde Akroenos adıyla, Selçuklu Hanedanından itibaren ise Karahisar adı ile anılmıştır.Tarihi dokusu korunamamış olsa da hala eski kalıntılar mevcuttur.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (2,3,'Ulu Camii','Afyonkarahisar Ulu Camii, Türkiye nin Afyonkarahisar ilinde yer alan bir camidir.1272-1277 yılları arasında Sahipata Nusrediddün Hasan tarafından ya da mihrapta adı geçen Sivastos oğlu Ali Bey tarafından[2] yaptırılmıştır. 40 ahşap sütun üzerinde oturtulmuş çatısı nedeni ile Kırk Direkli Cami olarak da anılır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (3,1,'','Adananın tarihçesi yaklaşık 3.000 yıl öncesine kadar uzanmaktadır. Bölgedeki arkeolojik bulgular, Paleolitik Çağa kadar uzanan insan yerleşimlerini ortaya çıkarmıştır. Tepebağ Höyüğü adında bir yerleşim yeri, arkeologlar tarafından taş bir duvar ve bir şehir merkezi olarak keşfedilmiştir. Bu höyük, Neolitik Çağda inşa edilmiş olup Çukurova bölgesindeki en eski şehir olarak düşünülmektedir.Adana ismi, Sümer destanlarından biri olan \"Gılgamış Destanı\"nda geçmektedir, ancak bu çalışmanın coğrafyası söz konusu yerin konumunu belirlemek için belirsizdir.Hitit Kaya yazıtlarına göre, MÖ 1335 dolaylarında Kizzuvatna adı verilen bir krallık, Hititlerin koruması altında Adanayı yöneten ilk krallıktır. Şehir, Uru Adaniya adıyla anılmış ve sakinleri Danuna olarak bilinmiştir. MÖ 1191-1189 yıllarında Hitit İmparatorluğunun çöküşüyle birlikte batı kaynaklı akınlar başlamış ve bölgenin kontrolü birçok küçük çaplı krallığa geçmiştir.Hititlerin ardından şehir, Geç Hitit Krallıklarından biri olan Hiyava veya Kuenin egemenliği altına girmiştir. Daha sonra Asurlular, Persler, Büyük İskender, Selevkoslar, Kilikya korsanları, Romalı devlet adamı Pompey ve Kilikya Ermeni Krallığı bölgenin denetimini ele geçirmişlerdir.Adananın tarihçesi, temel olarak Tarsusun tarihçesiyle bağlantılıdır. Seyhan Nehrine komşu olan bu iki şehrin konumu zamanla nehir tarafından değiştirilmiştir, bu nedenle bu şehirler sıklıkla aynı kent olarak anılmış ve isimleri asırlar boyunca değişmiştir. Romalılar döneminde Adana, göreceli olarak daha az öneme sahipti ve bölgenin metropolü olarak Tarsus öne çıkmaktaydı. Gnaeus Pompeius Magnus döneminde şehir, Kilikya korsanları için bir hapishane olarak kullanılmıştır. Birkaç yüzyıl sonra, şehirde Roma askeri yolu üzerinde yerel bir istasyon kurulmuştur. MS 395 te Roma İmparatorluğunun tam çöküşünden sonra bölge, Bizans İmparatorluğunun bir parçası haline gelmiş ve muhtemelen Julianus döneminde gelişmiştir.Adana ve Kilikya bölge, büyük köprülerin, yolların, hükümet binalarının, sulama ve fidanlıkların inşasıyla en önemli ve gelişmiş ticaret merkezlerinden biri haline gelmiştir. Özellikle Kilikyalılar döneminde Ayas (Yumurtalık) ve Kozan (Sis) bölgenin diğer büyük şehirleri ve yönetim merkezleri olmuşlardır.Adana tarih boyunca Luvi Krallığı, Arzava Krallığı, Hitit İmparatorluğu, Asurlular, Pers İmparatorluğu, Helenistik Yunan Uygarlığı, Selevkos İmparatorluğu, Kilikya Prensliği, Romalılar, Bizans İmparatorluğu, Abbasiler, Büyük Selçuklu İmparatorluğu, Memlükler, Ramazanoğlu Beyliği, Osmanlı İmparatorluğu ve Türkiye egemenliği altında kalmıştır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (3,2,'','Adıyaman, tarihin bilinen en eski yerleşim yerlerinden biridir. Adıyaman Palanlı Mağarasında yapılan incelemelerde kent tarihinin M.Ö. 40000 yıllarına kadar uzandığı anlaşılmıştır.Yine Samsat-Şehremuz Tepedeki tarihi bulgulardan M.Ö. 7000 yılına kadar Paleolitik, M.Ö. 5.000 yıllarına kadar Neolitik, M.Ö. 3000 yıllarına kadar Kalkolitik ve M.Ö. 3000-1200 yılları arasında da Tunç Çağı dönemlerinin yaşandığı anlaşılmıştır.Bu dönemde bölge Hititlerle Mitannilar arasında el değiştirmiş ve Hitit Devletinin yıkılmasıyla (M.Ö. 1200) karanlık bir dönem başlamıştır. M.Ö. 1200 den Frig Devletinin kuruluşu olan M.Ö. 750 yıllan arası dönemle ilgili olarak yazılı kaynağa rastlanmamıştır.Ancak; bu dönemde yöre, Asur etkisine girmeye başladığından, Samsat ta bulunan Asur etkili mühürler ve Kahta Eskitaş Köyünde bulunan Hitit Hiyeroglifi ile yazılmış kitabeler, Anadoludaki tarihi silsilenin ilimizde de aynen devam ettiğini, göstermektedir.Bu dönemde Adıyaman ve çevresinde Hitit Devletinin yıkılmasıyla ortaya çıkan Geç Hitit şehir devletlerinden biri olan Kummuh Devleti hüküm sürmüştür.M.Ö. 900-700 yılları arasında yöre Asur etkisinde kalmakla birlikte, Asurlular tam olarak egemen olamazlar. 6. yüzyılın başlarından itibaren yöreye Persler hakim olur ve yöre Satraplar (Valiler) eliyle yönetilir.M.Ö. 334 yılında Makedonya Kralı Büyük iskenderin Anadoluya girmesiyle Persler hakimiyetini kaybetmiş ve M.Ö. 1. yüzyıla kadar yörede Makedonyalı Seleukos Sülalesi hüküm sürmüştür.Bu sülalenin gücünün zayıfladığı sıralarda, Kral Mithradetes l Kallinikos Kommagene Krallığının bağımsızlığını ilan etmiştir (M.Ö. 69).')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (3,3,'','Adıyamanın tarihi MÖ 3000 yılına kadar uzanmaktadır. M.Ö. 2000 li yılların başında Hattilerin egemenliği altında olan yerleşim, M.Ö. 2. binyılın ortalarında Hititlerin kontrolüne geçmiştir.Hitit İmparatorluğunun çökmesiyle birlikte, M.Ö. 1000 civarında yerleşim Friglerin egemenliği altına girmiştir. Frigler döneminde kale içine \"Akronium\" adı verilmiş ve daha sonra bu isim şehir içinde kullanılmaya başlanmıştır. M.Ö. 6. yüzyılın sonlarına doğru Friglerin hakimiyeti sona ermiş ve yerleşim Perslerin kontrolüne geçmiştir. Pers egemenliği, M.Ö. 333 yılında Makedon Kralı III. Aleksandros tarafından yapılan İssos Savaşında alınan bir yenilgiyle sona ermiştir.M.Ö. 30 lu yıllardan itibaren yerleşim, Roma İmparatorluğunun egemenliği altına girmiştir. Bu dönemde yerleşime \"Akroenos\" adı verilmiştir. Roma İmparatorluğunun MS 395 yılında bölünmesiyle yerleşim Bizans İmparatorluğu topraklarında kalmış ve \"Akronion\" adını almıştır.12. yüzyılın sonlarında yerleşim Türk egemenliğine geçmiştir. Anadolu Selçuklu Devletinin Kösedağ Muharebesinde aldığı yenilgi sonucunda, bölge vezir Sâhib Ata Fahreddin Alinin kontrolüne verilmiş ve 1275 yılında Afyonkarahisarın başkenti olduğu Sâhib Ataoğulları Beyliği kurulmuştur. 1341 yılında Germiyanoğulları Beyliğinin topraklarına katılan yerleşim, 1390 yılında Osmanlı egemenliğine geçmiştir. 1402 yılındaki Ankara Savaşı sonucunda Afyonkarahisar tekrar Germiyanoğullarının eline geçmiştir. Ancak II. Yakub Beyin vasiyeti üzerine, yerleşim 1429 yılında yeniden Osmanlı egemenliğine katılmıştır.Osmanlı döneminde, başlangıçta \"Karahisar-ı Devle\", \"Karahisar\" ve \"Karahisar-ı Sahib\" gibi adlarla anılan yerleşim, 1684 yılından itibaren \"Afyonkarahisar\" adıyla da anılmaya başlanmıştır. Yerleşim, 1833 yılında Kavalalı İbrahim Paşanın kuvvetleri tarafından ele geçirilmiş, ancak aynı yıl içinde tekrar Osmanlı egemenliğine geçmiştir.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (4,1,'Adana Kebab','Adana kebabı, şehrin adını en çok duyurduğu bugün ülkemizin dört bir yanında restoranlarda Adana dürüm, Adana kebap olarak menülere giren lezzetidir.Adana’nın meşhur lezzeti Adana kebabını her yerde deneyimleyebilirsiniz ancak gerçek anlamda bir Adana kebap yemek isterseniz rotanızı kebabın ana vatanı olan Adana’ya yöneltmelisiniz.Adana’nın dürümcülerinde ve restoranlarında kolayca bulabileceğiniz Adana kebap acılı ve acısız seçenekleri ile müşterilere sunuluyor.Adana kebap yapılırken kullanılan dana kıyma ve kuzu kıyma, baharatlar ve tabi ki yöresel salça, tarifi ana vatanında deneyimleyenlerin çok daha leziz bulmasının nedenleri arasında yer alıyor.Birçokları tarafından evlerde dahi denenen Adana kebap asıl olarak yapılırken birçok püf noktası bulunan bir lezzet. Bu nedenle de gerçek bir Adana usulü kebap yemek isterseniz yine gitmeniz gereken yer Adana olacaktır.Yöresel lezzetlerinden tutun da salçasının tadına kadar özgünlük kokan bu şehirde Adana kebap yemeye doyamayabilirsiniz.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (4,1,'Ciğer','Ciğer, Adana’da bir anlamda marka haline gelmiş bir lezzettir.Onu bu kadar özel yapan ise kahvaltıda tüketiliyor olması.Daha önce hiç kahvaltıda ciğer yemediyseniz bu size biraz tuhaf gelebilir.Ancak ciğer Adana’da sıkça kahvaltıda tüketiliyor. Adana usulü ciğerin kahvaltıda tüketiliyor olması turistlerin de bir hayli ilgisini çeken lezzetler arasına girmesini sağlıyor.Sadece kahvaltıda tüketilmesi değil aynı zamanda insana yedikçe yediren lezzeti sayesinde her kahvaltıda ciğer yemek isteyebilirsiniz.Ciğeri kahvaltıda sunmak Adana için çok uzun zamandır gelenek haline gelmiş bir alışkanlık. Her hafta Pazar günleri sokakların ara kesimlerinde kebapçıların ocaklarında ciğer pişirdiğini görebilirsiniz.Geçmişten bugüne bir gelenek olarak devam eden ve sokak aralarında hayat bulan kahvaltıda ciğer yeme alışkanlığı şehre turist olarak gelenlerin en çok şaşırdığı geleneklerden biri.Ciğer deneyimlemek isterseniz sokak aralarında bulunan ciğercilere uğrayabilir ve taburede otururken yiyebilirsiniz.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (4,2,'Çiğköfte','Türk mutfağının en sevilen ve en çok bilinen lezzetlerinden biri olan çiğ köfte,başka yörelerde farklı şekillerde yapılsa da Adıyaman yöresine ait bir yemek olarak karşımıza çıkar.Özellikle sıra gecelerinin vazgeçilmezi olan çiğ köftenin yoğrulması, tavana atılması bir ritüel havasında geçmektedir.Genellikle ince uzun köfte şeklinde hazırlanır ve marulla servis edilir.Çiğ köfte yapıldığı yöreye göre etli ya da etsiz tercih edilirken çiğ etin hastalıklara neden olabilmesi nedeniyle Adıyaman çiğ köfte genellikle etsiz tercih edilmektedir.Bulgur ağırlıklı bir yemek olan çiğ köfte yoğrulurken isot, salça, soğan, maydanoz ve çeşitli baharatlar kullanılır ve tatlandırılır.Bulgurun beklerken şişebilmesinden dolayı tazeyken yenmesi gereken çiğ köfte günümüzde en çok aranan sokak lezzetlerinden biri olmuştur.Özellikle Adıyaman çiğ köfte mutlaka herkesin tatması gereken lezzetlerin başındadır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (4,2,'Besni Tava','Adıyaman mutfağının sevilen yemeklerinden biri olan Besni Tavası bol bol sebze ve etin buluştuğu bir yemektir.Adıyaman’ın Besni ilçesinde neredeyse her köşede yapılan bu fırın yemeği bölgeye giden turistlerin oldukça ilgisini çekmektedir.Görünüş açısından kolay bir yemek gibi görünse de içerisindeki kuzu etinin,soğanın, patlıcanın, biberin, domatesin küp küp doğranması oldukça zaman almaktadır.Tüm bu malzemeler tepsiye dizildikten sonra yemeğin lezzetini arttırmak için üzerine kuyruk yağı eklenir ve yemek lezzetine lezzet katmak için mahalle fırınına pişmeye verilir.Eğer Besni’ye yolunuz düşerse herhangi bir kasaba gidip kaç kişilik Besni tavası istediğinizi söylüyorsunuz, kasap sizin için tüm malzemeleri hazırlayıp mahalle fırına gönderiyor ve yemeğiniz hazırlanıyor.Herkesin mutlaka tatması gereken bu mükemmel lezzeti yemeden Adıyaman’dan dönmek imkânsızdır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (4,3,'Çullama Köfte','Afyon, seyahat edeceğiniz yerler arasında yer alıyorsa, yemeden dönmemeniz gereken bazı lezzetler bulunuyor.Bu lezzetlerin başında, içinde özel baharatlarla harmanlanıp hazırlanan çullama köftesi geliyor. Çullama köftesi yalnız lezzeti ile değil aynı zamanda görüntüsüyle de tam not almayı başaran lezzetlerden biridir.Çullama köftesinde hem lezzetli iç harçlar hem de özel sos kullanılır. Böylece köftenin lezzet oranı daha da fazla arttırılmış olur. Afyon, yemek kültürüyle de adından söz ettiren bir şehrimiz olmayı başarıyor.Bu yemeğin en güzel tarafı, doyurucu olmasıdır. Hem mideye hem de göz zevkine hitap eden meşhur yemeklerinden biridir. Çullama köftesi kıyma, soğan, baharat, yumurta, maydanoz gibi malzemeleri içerisinde barındıran bir yemektir.Hem yaz hem de kış aylarında dilediğiniz zaman tüketebilirsiniz. Fakat köftenin daha ağırlıklı şekilde tüketildiği mevsim genelde kış ayları oluyor.Afyon’a ziyaret yapacak olan kişilerin mutlaka farklı tarifiyle sizi şaşırtacak çullama köftesini denemesi gerekiyor.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (4,3,'Keşkek','Düğünlerin ve özel davetlerin olmazsa olmaz yemeklerinden biri keşkek yemeğidir. Şüphesiz ülkemizde keşkek yemeğini bilmeyen yoktur.Zahmetli diyebileceğimiz bir yemek olduğundan dolayı, yaparken güç ister.Keşkek daha çok Afyon’un Şuhut ilçesinde ağırlıklı şekilde yapılır. Öyle ki Şuhut ilçesinin tescil ettiği yemeklerinden biridir.Çok lezzetli bir yemek olduğundan dolayı herkes tarafından da sevilerek tüketilmektedir. Fakat lezzetli olduğu kadar aynı zamanda oldukça zahmetlidir.Bu yüzden keşkek daha çok özel günlerde yapılan yemek haline gelmiştir.Keşkek içerisinde buğday, kuşbaşı et, nohut, nane, tuz, tereyağı, salça gibi malzemeler yer alır.Keşkek içerisine eklenecek olan et, kırmızı ya da beyaz et olacak biçimde tercih edilebilir. Bazı yörelerde tavuk eti kullanılırken, Afyon şehrinde kuşbaşı et kullanılır.Eğer ki Afyon yolculuğu yapıyorsanız, zahmetli ve lezzetli olan keşkek yemeğini yemeden dönmeyin.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (5,1,'','Adana yöresi,Kürt,Türk ve Arap kültürlerinin harmanlanmasından oluşmuş çok karmaşık bir kültüre sahiptir.Geleneksel giyim olarak, Adananın yöresel kıyafeticşalvardır. Ayrıca bele kuşak da bağlanır. Erkekler \\\"burma bıyık\\\" bırakır.Kasket, göğüs açık beyaz gömlek, siyah yelek, siyah \\\"Adana Şalvarı\\\", beyaz çorap, yumurta topuklu ve sivri burunlu kösele ayakkabı yörede oldukça tercih edilen bir giyim biçimidir.Geleneksek yiyecek ve içecekler olarak, yöredeki yemeklerin en önemli yanı un, bulgur, et, sebze ve çeşitli baharatların çok kullanılmasıdır. Yemeklerin yanında bol yeşillik ve salatalar tüketilmektedir. Özellikle etli yemekler sebze ile birleştirilerek pişirilir.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (5,2,'','Adıyaman yöresi, kültürel açıdan oldukça zengin bir yöredir. Yörede hafife alınamayacak kadar tarihi yerler bulunmaktadır.Bunların içerisinde de Nemrut Dağı Ören Yeri bulunmaktadır. Adıyamada tarihi kaleler, kaya mezarlar, cami ve kiliseler bulunmaktadır. Bu tarihi zenginliğin içerisinde yöre kültürel anlamda oldukça zengin yapıdadır.Yöresel yiyecekler açısından,yöre yemeklerinin temel maddeleri olarak buğday ürünleri, kuru baklagiller, patlıcan, domates ve lahana kullanılmaktadır. Soğan, sarımsak, salça, pul biber, maydanoz ve baharatlar tüm yemeklerde tat verici olarak kullanılmaktadır.El sanatları açısından,yörede kanaviçe ve yazmalar hala yapılmaktadır.Köşkerlik ( yemenicilik ) ise gelişen teknoloji karşısında hemen hemen yok olmuştur.Adıyaman ilçe ve köylerinde aşağıdaki el sanatları yapılmaktadır.Halk oyunları açısından, Adıyaman yöresi halk oyunları, diğer halk oyunları yöreleri gibi bulunduğu bölgenin doğal şartlarının,inanışlarının, yaşanmışlıklarının müzik ve figürler ile tercümanı olmuştur.Giyim kuşam açısından Kıyafetleri günümüzde de kırsalda kullanılmaktadır. Dağ köylerinde kıl kumaştan yapılmış şalvar, Aba denilen ceket ve yakasız gömlekten ibarettir. Ayakta çorap ve yemeni bulunmaktadır. Şalvar ve yakalı veya yakasız gömlekle bütünleşen kıyafetin üzerine “fillik kuşak “ denilen ipek, püsküllü, beyaz renkte bir kuşak sarılmaktadır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (5,3,'','Afyonkarahisar yöresi Ege Bölgesnden İç Anadolu Bölgesine geçiş noktasında bulunmaktadır. Bu yüzden bu bölge halkında oldukça çeşitlilik mevcuttur.Bu çeşitlilik yörenin kültürüne de yansımış ve oldukça zengin bir kültür oluşturmuştur.Yiyecek ve içecekler açısından, Ege Bölgesinde bulunan yöre mutfak açısından daha çok İç Anadolu Bölgesine benzemektedir.Et yemekleri, sebze yemekleri ve hamur işi Afyon mutfağında önemli yer tutmaktadır. Afyon kaymağı ve sucuğu ile de oldukça meşhur bir yöredir.Afyon kaymağı yöre ekonomisine oldukça önemli katkı sağlamaktadır.El sanatları açısından, Afyon ilinde kilimcilik oldukça gelişmiştir. Kilimciliğin yanı sıra ilçe ve köylerde genç kızların çeyizleri için yaptıkları el işleri de bulunmaktadır.El sanatları açısından, Afyon ilinde kilimcilik oldukça gelişmiştir.Kilimciliğin yanı sıra ilçe ve köylerde genç kızların çeyizleri için yaptıkları el işleri de bulunmaktadır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (6,1,'','Otobüs: Adana da geniş bir otobüs ağı bulunmaktadır. Şehir içindeki pek çok noktaya otobüs seferleri düzenlenmektedir. Otobüsler genellikle yoğun saatlerde ve ana güzergahlarda sık seferler yapmaktadır.\n Metro: Adana da 2 metro hattı bulunmaktadır: M1 ve M2. M1 metro hattı, Hastane - Vilayet arasında hizmet verirken, M2 metro hattı, Yüreğir - Çukurova Üniversitesi arasında faaliyet göstermektedir. Metro seferleri genellikle sabahın erken saatlerinden gece yarısına kadar devam etmektedir.\nTramvay: Adana da 2 tramvay hattı bulunmaktadır: T1 ve T2. T1 tramvay hattı, Huzurevleri - Balcalı arasında, T2 tramvay hattı ise Hastane - Reşatbey arasında hizmet vermektedir. Tramvay seferleri sabahın erken saatlerinden gece yarısına kadar devam etmektedir.\nMinibüs: Adana da minibüsler yaygın bir ulaşım aracıdır. Farklı güzergahlarda sefer yapan minibüslerle şehir içinde ulaşım sağlayabilirsiniz. Minibüsler genellikle otobüs hatlarına ek olarak daha küçük mahallelere ve semtlere hizmet vermektedir.\nTaksi: Adana da taksi hizmeti oldukça yaygındır. Taksiyle istediğiniz noktaya kolaylıkla ulaşabilirsiniz. Adana da taksilerin genellikle taksi duraklarında veya sokaklarda bulunan taksi duraklarında bulunan taksi duraklarından veya mobil uygulamalar aracılığıyla çağırabilirsiniz.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (6,2,'','Otobüs: Adıyaman da otobüslerle şehir içi ulaşım sağlamak mümkündür. Otobüsler genellikle ana caddeler boyunca belirli güzergahlarda seferler düzenler. Otobüslerin sık seferleri vardır ve şehirdeki çoğu noktaya ulaşım imkanı sağlar.\nMinibüs: Adıyaman da minibüsler yaygın bir ulaşım aracıdır. Farklı güzergahlarda sefer yapan minibüslerle şehir içinde dolaşabilirsiniz. Minibüsler, otobüs hatlarına ek olarak daha küçük mahallelere ve semtlere hizmet verir.\nTaksi: Adıyaman da taksiler de şehir içi ulaşımda tercih edilen bir seçenektir. Taksileri çağırmak için taksi duraklarından veya mobil uygulamalar aracılığıyla hizmet alabilirsiniz. Taksiyle istediğiniz noktaya daha hızlı ve konforlu bir şekilde ulaşabilirsiniz.\nÖzel Araç: Kendi aracınız varsa veya araç kiralama yapıyorsanız, Adıyaman da şehir içindeki yerlere özel aracınızla kolayca gidebilirsiniz. Şehirde genellikle park alanları bulunmaktadır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (6,3,'','Otobüs: Afyonda otobüsler şehir içi ulaşımda yaygın olarak kullanılan bir seçenektir. Otobüsler genellikle ana caddeler boyunca belirli güzergahlarda sefer düzenler. Şehirdeki önemli noktalara otobüslerle kolayca ulaşabilirsiniz.\nMinibüs: Afyon da minibüsler, şehir içi ulaşımda sıkça tercih edilen bir seçenektir. Minibüsler, otobüslerden daha küçük güzergahlarda hizmet verir ve daha küçük mahallelere ulaşımı sağlar. Minibüsler genellikle belirli hatlarda sefer yapar.\nTaksi: Afyon da taksiler, hızlı ve konforlu bir şehir içi ulaşım seçeneğidir. Taksileri çağırmak için taksi duraklarından veya mobil uygulamalar aracılığıyla hizmet alabilirsiniz. Taksilerle istediğiniz noktaya kolayca gidebilirsiniz.\nÖzel Araç: Kendi aracınız varsa veya araç kiralama yapıyorsanız, Afyon da özel aracınızla şehir içinde rahatlıkla dolaşabilirsiniz. Şehirde genellikle park alanları bulunmaktadır.')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (7,1,'','')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (7,2,'','')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (7,3,'','')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (8,1,'','Adana Köprü Başı\nAdana Yollarında\nAğlarım (Yirmi Sene Gurbet Kahrı)')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (8,2,'','Telli Turna\nİki Kız Gider\nKara Dağın Boz Yılanı')");
        db.execSQL("INSERT INTO bilgiler_tablo (ozID,sehirId,baslik,aciklama) VALUES (8,3,'','Ben Giderim Oduna\nCevizin Yaprağı Dal Arasında\nDam Başına Asa Goymuş Galbırı')");



    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int i, int i1) {
        db.execSQL("DROP TABLE IF EXISTS sehirler_tablo");
        db.execSQL("DROP TABLE IF EXISTS ozellik_tablo");
        db.execSQL("DROP TABLE IF EXISTS bilgiler_tablo");
        onCreate(db);

    }






}
